[package]
name = "chipioindustries/make-standalone"
description = "Utility function for converting methods to standalone functions."
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]
t = "osyrisrblx/t@3.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"